
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phw-docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phw-docker
    spec:
      containers:
      - name: phw-docker
        image: registry.ng.bluemix.net/devname/devrepo:phw_docker
---
apiVersion: v1
kind: Service
metadata:
  name: phw-docker-service
  labels:
    app: phw-docker
spec:
  selector:
    app: phw-docker
  type: NodePort
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000